
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isvndtnffydzczfrorxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzdm5kdG5mZnlkemN6ZnJvcnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTY5ODQsImV4cCI6MjA2MDA5Mjk4NH0.U2f7Xq-h7cgnqwcd7RgvmCzlk2qf_g7ZwOQqqYFYrvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
